class Library {
    static AudioTrack[] LIBRARY = { new Song("Gangnam Style", 219, "Psy", MusicGenre.POP),
            new Song("Enter Sandman", 331, "Metallica", MusicGenre.METAL),
            new Song("Sad But True", 324, "Metallica", MusicGenre.METAL),
            new Song("Holier Than Thou", 227, "Metallica", MusicGenre.METAL),
            new Song("The Unforgiven", 390, "Metallica", MusicGenre.METAL),
            new Song("Wherever I May Roam", 403, "Metallica", MusicGenre.METAL),
            new Song("Don't Tread on Me", 240, "Metallica", MusicGenre.METAL),
            new Song("Through the Never", 244, "Metallica", MusicGenre.METAL),
            new Song("Nothing Else Matters", 388, "Metallica", MusicGenre.METAL),
            new Song("Of Wolf and Man", 256, "Metallica", MusicGenre.METAL),
            new Song("My Friend of Misery", 409, "Metallica", MusicGenre.METAL),
            new Song("The Struggle Within", 231, "Metallica", MusicGenre.METAL),
            new Podcast("The Joe Rogan Experience: Robert Kennedy, Jr", 10800, "Joe Rogan", PodcastGenre.COMEDY,
                    1999),
            new Song("Aces High", 271, "Iron Maiden", MusicGenre.METAL),
            new Song("2 Minutes to Midnight", 360, "Iron Maiden", MusicGenre.METAL),
            new Song("Losfer Words (Big 'Orra)", 263, "Iron Maiden", MusicGenre.METAL),
            new Song("Flash of the Blade", 256, "Iron Maiden", MusicGenre.METAL),
            new Song("The Duellists", 376, "Iron Maiden", MusicGenre.METAL),
            new Song("Back in the Village", 305, "Iron Maiden", MusicGenre.METAL),
            new Song("Powerslave", 423, "Iron Maiden", MusicGenre.METAL),
            new Song("Rime of the Ancient Mariner", 816, "Iron Maiden", MusicGenre.METAL),
            new Podcast("The Joe Rogan Experience: Mike Tyson", 9000, "Joe Rogan", PodcastGenre.COMEDY,
                    1532),
            new Song("Moonshield", 301, "In Flames", MusicGenre.METAL),
            new Song("The Jester's Dance", 202, "In Flames", MusicGenre.METAL),
            new Song("Artifacts of the Black Rain", 198, "In Flames", MusicGenre.METAL),
            new Song("Graveland", 203, "In Flames", MusicGenre.METAL),
            new Song("Lord Hypnos", 244, "In Flames", MusicGenre.METAL),
            new Song("Dead Eternity", 307, "In Flames", MusicGenre.METAL),
            new Song("The Jester Race", 274, "In Flames", MusicGenre.METAL),
            new Song("December Flower", 252, "In Flames", MusicGenre.METAL),
            new Song("Wayfaerer", 260, "In Flames", MusicGenre.METAL),
            new Song("No Gods But Our Flesh", 289, "Inferi", MusicGenre.METAL),
            new Song("Maelstrom Prison", 324, "Inferi", MusicGenre.METAL),
            new Song("Simian Hive", 305, "Inferi", MusicGenre.METAL),
            new Song("From Exile to Exaltation", 282, "Inferi", MusicGenre.METAL),
            new Song("Vile Genesis", 344, "Inferi", MusicGenre.METAL),
            new Song("Mesmeric Horror", 314, "Inferi", MusicGenre.METAL),
            new Song("Eye of the Tiger", 245, "Survivor", MusicGenre.ROCK),
            new Song("Feels Like Love", 270, "Survivor", MusicGenre.ROCK),
            new Song("Hesitation Dance", 235, "Survivor", MusicGenre.ROCK),
            new Song("The One That Really Matters", 221, "Survivor", MusicGenre.ROCK),
            new Song("I'm Not That Man Anymore", 280, "Survivor", MusicGenre.ROCK),
            new Song("Children of the Night", 297, "Survivor", MusicGenre.ROCK),
            new Song("Ever Since the World Began", 234, "Survivor", MusicGenre.ROCK),
            new Song("American Heartbeat", 240, "Survivor", MusicGenre.ROCK),
            new Song("Silver Girl", 269, "Survivor", MusicGenre.ROCK),
            new Song("Beat It", 258, "Michael Jackson", MusicGenre.POP),
            new Song("Ode To Joy", 660, "Ludwig van Beethoven", MusicGenre.CLASSICAL),
            new Podcast("Lex Fridman Podcast: Mark Zuckerberg", 3840, "Lex Fridman", PodcastGenre.TECHNOLOGY,
                    398),
            new Podcast("Lex Fridman Podcast: Elon Musk on SpaceX", 7200, "Lex Fridman", PodcastGenre.TECHNOLOGY,
                    420),
            new Podcast("Lex Fridman Podcast: Jordan Peterson on Life", 5400, "Lex Fridman",
                    PodcastGenre.TECHNOLOGY, 421),
            new Podcast("Lex Fridman Podcast: Joe Rogan on Podcasting", 4800, "Lex Fridman",
                    PodcastGenre.TECHNOLOGY, 422),
            new Podcast("Lex Fridman Podcast: Tim Ferriss on Self-Optimization", 3600, "Lex Fridman",
                    PodcastGenre.TECHNOLOGY, 423),
            new Podcast("Lex Fridman Podcast: Andrew Ng on Artificial Intelligence", 3900, "Lex Fridman",
                    PodcastGenre.TECHNOLOGY, 424),
            new Podcast("Lex Fridman Podcast: Vitalik Buterin on Ethereum", 4300, "Lex Fridman",
                    PodcastGenre.TECHNOLOGY, 425),
            new Podcast("Lex Fridman Podcast: Garry Kasparov on Chess and AI", 3100, "Lex Fridman",
                    PodcastGenre.TECHNOLOGY, 426),
            new Podcast("Lex Fridman Podcast: Robert Sapolsky on Biology", 5000, "Lex Fridman",
                    PodcastGenre.TECHNOLOGY, 427),
            new Podcast("Lex Fridman Podcast: Sam Harris on Consciousness", 3800, "Lex Fridman",
                    PodcastGenre.TECHNOLOGY, 428)
    };
}